#!/usr/bin/env ruby
require 'optparse'
require 'ostruct'
require 'yaml'
require 'pry'
require 'pry-byebug'
require 'pry-stack_explorer'
$LOAD_PATH << File.expand_path('../lib', __FILE__)

SO2_ROOT = "#{File.expand_path('..', __FILE__)}"
SO2_SETTING_FILE = "#{SO2_ROOT}/setting.yml"

begin
  SO2_SETTING = YAML.load_file(SO2_SETTING_FILE)
rescue Errno::ENOENT
  puts "There is not #{SO2_SETTING_FILE}"
  exit
end

prj_root = `git rev-parse --show-superproject-working-tree`.strip
prj_root = `git rev-parse --show-toplevel`.strip if prj_root.empty?
PRJ_ROOT = prj_root
SO2_CONFIG_FILE = "#{prj_root}/.so2.yml"
begin
  SO2_CONFIG = YAML.load_file(SO2_CONFIG_FILE)
rescue Errno::ENOENT
  puts "There is not #{SO2_CONFIG_FILE}"
  SO2_CONFIG = {}
end

@available_subcommand = Dir.entries("#{SO2_ROOT}/subcommands").select { |f|
  File.file?(File.join("#{SO2_ROOT}/subcommands",f))
}.map {|f| f.gsub("\.rb", "")}

def puts_available_subcommand
  puts "The available commands are:"
  @available_subcommand.each do |f|
    puts "\t#{f.gsub("\.rb", "")}"
  end
end

subcommand = ARGV.shift
if ["--help", "-h", "", nil].include? subcommand
  puts "usage: so2 [-h|--help] <command> [<args>]"
  puts ""
  puts_available_subcommand
  exit
end

unless @available_subcommand.include? subcommand
  puts "ERROR: Unknown subcommand #{subcommand}"
  puts ""
  puts_available_subcommand
  exit
end

subcommand_file = File.expand_path("../subcommands/#{subcommand}.rb", __FILE__)
require subcommand_file
